// Code generated by dagger-compiler.  Do not edit.
package com.riis.dagger;

import dagger.internal.ModuleAdapter;

/**
 * A manager of modules and provides adapters allowing for proper linking and
 * instance provision of types served by {@code @Provides} methods.
 */
public final class DisasterAppObjectGraph$$ModuleAdapter extends ModuleAdapter<DisasterAppObjectGraph> {
  private static final String[] INJECTS = { "members/com.riis.DisasterAppActivity", };
  private static final Class<?>[] STATIC_INJECTIONS = { };
  private static final Class<?>[] INCLUDES = { };

  public DisasterAppObjectGraph$$ModuleAdapter() {
    super(com.riis.dagger.DisasterAppObjectGraph.class, INJECTS, STATIC_INJECTIONS, false /*overrides*/, INCLUDES, true /*complete*/, false /*library*/);
  }

  @Override
  public DisasterAppObjectGraph newModule() {
    return new com.riis.dagger.DisasterAppObjectGraph();
  }
}
